name: Pull Request

on: ['pull_request', 'workflow_dispatch']

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    strategy:
      matrix:
        node: [18.x, 20.x, 21.x, 22.x]
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Turbo build
        run: pnpm turbo build

      - name: Lint, Prettier, and Typecheck
        run: pnpm lint:ci

      - name: Test packages
        run: pnpm test
        env:
          VITE_BLIZZARD_CLIENT_ID: ${{ secrets.BLIZZARD_CLIENT_ID }}
          VITE_BLIZZARD_CLIENT_SECRET: ${{ secrets.BLIZZARD_CLIENT_SECRET }}
